src/dataService.js, src/routes/CensusAtlas.svelte, src/stores.js, src/utils.js
We have refactored the app so that it stores the total category counts in global state when the first request is made.
=> checks and caches category totals

src/dataService.js, src/routes/CensusAtlas.svelte, src/services/flatfileGeographyService.js, src/services/mockGeographyService.js, src/stores.js, src/stores/geography.js, src/stores/geography.test.js, src/utils.js
-Creates geography service
-Refactors data handling functions for improved readability
-Moves several helper functions from CensusAtlas component to utils.js
=> Methods feature/refactors data handling functions

src/ui/ExampleComponent.stories.svelte, src/ui/ExampleComponent.svelte
Fairly self explanatory Example Component making use of ONS Design System for Storybook.
=> Add ExampleComponent

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSHeader.svelte
I have created a header component based on just the ONS logo as specified in the wireframes.
=> adds responsive header with just ONS logo

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSSelect.svelte
These fixes are necessary to unblock `npm run format`.
=> Fix ONSSelect

src/routes/DesignSystemApp.svelte, src/ui/ExploreByAreaComponent.svelte, src/ui/ons/svg/SearchIcon.svelte
I have added the explore by area component, it looks more or less like the one attached to the ticket.
My concerns are around the following:
- font in general(family/size)
- grid
- no class is applied on the p tag
And because I'm having doubts on how I created the component, it would have been better to use instead in the component (bottom-->top):button>>input with no label>>hint>>paragraph>>heading4?
=> Feature/explore by area component-ticket#63

src/routes/DesignSystemApp.svelte, src/ui/Feedback.svelte
I have created a feedback component based on code found in other ONS Digital repos.  There are some issues with responsiveness when it's embedded within the ONSCensusApp component, but not when it's outside, so I think it's probably not something worth troubleshooting until we know the container it will be wrapped in, especially given that the component behaves as we want it to at mobile view dimensions:
.
=> adds feedback component

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSExternalHeaderWithDescription.svelte
=> adds header to tidy up design system page

src/App.svelte, src/routes/DesignSystemApp.svelte
Prettier did quite a lot in there. Sorry, not sorry!
=> Make menu accessible in legacy version and fix build

src/routes/Components.svelte, src/routes/DesignSystemApp.svelte, src/ui/TopicExplorer.svelte, src/ui/ons/ONSAccordion.svelte, src/ui/ons/partials/ONSAccordionPanel.svelte
@thomasridd I populated ONSAccordian with census data from simpleTopicTablecategoryData file,  please let me know if this is all you wanted to display in the accordion.
Questions:
1. href does not have a value, yet, should I do something with that ?
2. I have modified the ONSAccordion component so should I actually do another component that we can use in our prototype and leave the ONS one as it is with the show all button at the top ?
3. The data is imported directly in the component, so instead should I do the import in the main component (prototype screen) and after pass it down as a property ?
=> Feature/populate topic explorer component-ticket#70

src/data/mapstyle.js, src/ui/Map.svelte
Update <Map /> to be a simple map, not just a grey box
=> Simple map component

src/routes/ExploreCensus.svelte
This one got lost somehow. 🤷‍♂️
=> Add missing section

src/ui/ExploreByTopic.svelte
=> adds health route to explore by topic component

src/routes/ExploreCensus.svelte, src/ui/ExploreByAreaComponent.svelte, src/ui/ExploreByTopic.svelte, src/ui/Topic.svelte, src/ui/ons/ONSCard.svelte, src/ui/ons/ONSShare.svelte
N.B. as you can see to do this I added stylings to ONSShare and ONSCard - something to think about / reverse later.
=> adds margin-bottom to necessary components

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSAutosuggest.svelte
Add `<ONSAutosuggest />` component :
=> Feature/design system autosuggest - ticket#88

src/routes/__layout.svelte
=> Update example urls

src/ui/BasePage.svelte
What title says. Just a quick fix.
Fixes #98.
=> Remove extra wrapper padding on desktop

src/routes/components.svelte, src/routes/design-system.svelte, src/routes/index.svelte
As requested by Lynsey (https://onswebsite.slack.com/archives/C02KR4Y5GDQ/p1638378419077200), I have changed the header text.
=> changes header text

src/model/censusdata/services/geodataApiDataService.js, src/model/utils.js
We have refactored the dataByGeography structure to be a two dimensional Map.  This makes it more consistent with the selectedGeographyData store, and allows for straightforward and performant iteration over the data.
=> refactores the cached data structure to use a 2d Map

src/config.js, src/routes/[topicSlug].svelte, src/routes/[topicSlug]/[tableSlug]/[categorySlug].svelte, src/routes/area/index.svelte, src/routes/categories.svelte, src/routes/categories/[topicSlug].svelte, src/routes/index.svelte, src/ui/map/BoundaryLayer.svelte, src/ui/map/InteractiveLayer.svelte
**What**
I have updated the map layer order and I have also added the LAD map interactive layer across all screens. At the moment there is no LSOA level map interaction, as agreed today in the refinement session.
=> Feature/map layers order - ticket#173

src/routes/[topicSlug].svelte, src/routes/[topicSlug]/[tableSlug]/[categorySlug].svelte, src/routes/area/index.svelte, src/routes/categories.svelte, src/routes/categories/[topicSlug].svelte, src/routes/index.svelte, src/ui/Header.svelte, src/ui/TopicExplorer.svelte
**What**
I've made the map interactive so that when you select a geography by clicking the map, the data displayed in the `<CensusTableByLocation />` component gets updated accordingly. I've also added the map `<DataLayer />` component on the` routes/categories.svelte` screen. 
When a user lands on the home screen and selects a geography by clicking the map, the user gets redirected to the `routes/area/index.svelte` screen.
**How to review**
To review this PR just go through all the screens and interact with the map and simulate the possible/existing user journeys.
=> Feature/map interaction - ticket#215

src/data/apiMetadata.js
commit 40bdbd1a3af52c3dd84efcc7f72e40a1f2f1012a (HEAD -> feature/updated-canned-metadata-for-dac, origin/feature/updated-canned-metadata-for-dac)
Author: Vivian Allen <vivian.allen@methods.co.uk>
Date:   Mon Jan 24 13:42:41 2022 +0000
update src/data/apiMetadata.js with latest census metadata
populate new metadata object in apiMetadata.js with latest
medata from
https://docs.google.com/spreadsheets/d/1Q0Sckm8ss2gwTa4SROprYkKRQ1NJ-5MBzRiCiAFYUeE/edit#gid=0
=> update src/data/apiMetadata.js with latest census metadata

src/data/apiMetadata.js
chance all display-text fields in metada to Sentence case for easier rendering / better accessibility
=> update apiMetadata.js with sentence-case display text

src/ui/map/DataLayer.svelte, src/utils.js
=> fixes the ckmeans bug

src/model/geography/geography.js
**What**
We've fixed the map layer error messages showing up in the browser console.
=> Feature/fixes console map layer error msg - ticket#213

src/routes/[topicSlug]/[tableSlug]/[categorySlug].svelte, src/routes/components.svelte, src/ui/CategorySelector/CategorySelector.svelte, src/ui/CensusTableByLocation.svelte, src/ui/DataComparison/DataComparison.svelte, src/ui/DataHeader.svelte
Please merge #128 first as this was branched off it.
See commit log for tweak details.
=> Various CSS fixes to better align with Figma before DAC

README.md, src/routes/__layout.svelte
=> Remove dev nav

src/config.js, src/ui/ExploreByAreaComponent.svelte, src/ui/ons/ONSAutosuggest.svelte
https://trello.com/c/Q2FSJ0rx/220-improve-messages-for-geography-selection
=> Geography selection copy changes

src/config.js, src/ui/map/Map.svelte, src/ui/map/TileSet.svelte
Bounding box, signed off by Lynsey.
The map no longer allows you to pan across the world and is locked to England and Wales borders. This fixes boundary and OSM network errors from flooding the console.
=> Fix: Added bounding box to map, fixed issue with boundary and OSM 403 network errors.

src/ui/DataHeader.svelte
Disclaimer: I've already started working on a new iteration of `<DataHeader />` but didn't realise this wasn't in so throwing it in just for the record.
=> Add level one headings

MAPTILES.md
commit eb5c3ae645a51d9aaa777d6bc98d324059af8f96 (HEAD -> add-map-tile-guide-and-dir, origin/add-map-tile-guide-and-dir)
Author: Vivian Allen <vivian.allen@methods.co.uk>
Date:   Fri Mar 4 15:32:06 2022 +0000
MAPTILES.md guide to map tileset creation for census geography boundaries
=> Add map tile guide and dir

src/routes/[topicSlug]/[tableSlug]/[categorySlug].svelte, src/ui/UseCensusData.svelte
**What**
Updates the way the `<UseCensusData />` component displays on the map screen to match the V4 Design.
=> Updates UseCensusData component - ticket#416

src/routes/area/index.svelte
There is no longer a sex category so need to calculate the total number of people from a different category, just choose the first one in the list.
=> Fix: Fixed explore area data.
