package-lock.json, package.json, public/index.html, rollup.config.js, src/routes/DesignSystemApp.svelte, svelte.config.js
This makes use of Design System JS bundle, and exposes SCSS variables (while still relying on the whole CSS bundle).
Worth noting:
- We should probably reorganise file structure (both `ui/ons/components` and `public/build`) for clarity and to align with what SvelteKit uses by default but let's leave that until all code is integrated (or next sprint).
- "Our" DS components should ideally make use of their per-component JS files, but they seem to be buggy.
- The DS components should also ideally make use of their accompanied SCSS files, but ONS Design System uses a depracated Sass version (`node-sass`) and makes use of the glob `**/*` pattern (via `node-sass-glob-importer`) that `dart-sass` does not support. I'm checking with DS team whether they're going to move to Dart Sass, or whether we …
=> Improve Design System implementation

.gitignore, package-lock.json, rollup.config.js
Current master gives:
```
census-atlas git/master  
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: census-atlas@0.0.1
npm ERR! Found: svelte@3.31.2
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"3.31.2" from the root project
npm ERR!   peer svelte@"^3.1.0" from @storybook/svelte@6.3.12
npm ERR!   node_modules/@storybook/svelte
npm ERR!     dev @storybook/svelte@"^6.3.12" from the root project
npm ERR!     peer @storybook/svelte@"^6.2.9" from @storybook/addon-svelte-csf@1.1.0
npm ERR!     node_modules/@storybook/addon-svelte-csf
npm ERR!       dev @storybook/addon-svelte-csf@"^1.1.0" from the root project
npm ERR!   1 more (svelte-loader)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional …
```
=> Fix bundler

public/index.html, src/routes/DesignSystemApp.svelte
Not sure whether this is the right way but this makes sure the script fires back where actually needed.
This will be replaced by component specific JS anyway.
=> Makes sure ONS DS script is there each time DOM loads

src/ui/ExploreByAreaComponent.svelte
Removes the ons grid classes and changes the label to an h2 element
t.
=> Updates the explore by area component

src/ui/Topic.svelte
Removes the ons grid classes from the topic component.
=> Updates the topic component

src/ui/HeaderData2.svelte
I've used an ID to override several classes trying to enlarge the "In Walsall" heading.
=> fixes heading size

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSTextField.svelte, src/ui/ons/partials/ONSError.svelte
I have implemented on the ONSTextField component the changes from ticket#77. 
Things to have in mind when reviewing the PR :   
1. Svelte does not allow to have a dynamic type attribute. When I tried to set the type attribute as a props it was trowing a validation error ==> _ValidationError: 'type' attribute cannot be dynamic if input uses two-way binding_ so I had to use a fix which I found  on google.
2. Looks like it is recommended to avoid using a placeholder text  from an accessibility point of view according to this post : https://blog.cds.co.uk/top-tips-for-accessible-form-design  . So I am conditionally rendering the placeholder. 
3. For onChange handler I've used the on:input event instead of on:change because on:input occurs immediately after the value of an element has changed …
=> Feature/enhance text input-ticket#77

src/ui/ons/ONSBacklink.svelte
I have updated the `<ONSBacklink />` component so  that we can reuse it in the Census Atlas app. I have added an `inverted` props which renders the component on white when it is needed.
-  Default state:
- Added state:
=> ONS design system Backlink - toggles the component colour

src/routes/DesignSystemApp.svelte, src/ui/ons/ONSTextArea.svelte
I have updated the `<ONSTextArea />` component following the `<ONSTextField />` example and the associated trello ticket#89. 
**Differences :**  
1. The placeholder is passed down as a prop and I believe it is not accessible like the input one. I couldn't find an example of a text area with a placeholder text on the ONS DS page and neither an `ons class` that refers to a `text-area-placeholder` in the `main.css` file of the DS.
2. On the design system page I didn't add a `<p>` tag element to render the user input like I did on the `<ONSTextField />` component so let me know if we need that.
3. On the trello ticket#89 there was a check item for adding a `type` attribute as a prop on the `<ONSTextArea />`component ; I suspect that this is not actually applicable for a `<textarea>`element, …
=> Feature/design system text area - ticket#89

src/data/test/mockDSData.js, src/routes/DesignSystemApp.svelte, src/ui/ons/ONSSelect.svelte
I have updated the `<ONSSelect/>` component as per the trello ticket #84. 
And I've used the `on:change` event to disable the current selection.
=> Feature/design system select - ticket#84

src/data/test/mockDSData.js, src/routes/DesignSystemApp.svelte, src/ui/ons/ONSCheckboxes.svelte, src/ui/ons/partials/ONSCheckbox.svelte
I've completely refactored these 2 components `<ONSCheckbox />` and `<ONSCheckboxes />` following the [DS checkboxes example](https://ons-design-system.netlify.app/components/checkboxes/) and the ticket#85. While trying to apply the `bind:value` svelte directive I found out that in svelte the [`bind:group` does not work with nested components](https://github.com/sveltejs/svelte/issues/2308) and this is why I ended up using the `onChangeBindGroup` function as a solution.
=> Feature/design system checkboxes - ticket#85

src/config.js, src/routes/index.svelte, src/ui/BasePage.svelte, src/ui/ExploreByTopic.svelte, src/ui/map/Map.svelte
We have updated the Home screen as per the `trello ticket 115`, but what we haven't actually touched is the background image. Not sure what improvements are needed on that. 
According to the wireframes the home screen loads a non data map on desktop view, but not on mobile view so we had to conditionally render the map based on the window width and it looks like in svelte you [ can't have conditional slots](https://github.com/sveltejs/svelte/issues/5604) so to get around this we had to update the `<BasePage />` component.
We have also located the map on England & Wales on first load:
=> Feature/data driven home screen - #ticket115 

.npmrc, package-lock.json, package.json
This is to prevent re-creation of `package-lock.json` when using different NPM version is used.
=> Lock down NPM version

src/config.js
Update URLS for dp-geodata-api to match new ones merged [here](https://github.com/ONSdigital/dp-find-insights-poc-api/pull/166). This will be needed to merge once the new API is deployed.
=> update endpoint URLS for querying dp-geodata-api

src/ui/CategorySelector/DisplaySelectedCatFigures.svelte, src/ui/MapKey/MapKey.svelte
We fixed a bug with the colour scheme which was causing the original colour legend array in config to reverse.
=> fixes colour reverse bug

src/model/utils.js, src/ui/map/DataLayer.svelte
Fixed an issue with map data not loading following this user journey "Choose a category" > "Housing" > "Heating" > "Gas".
The issue is due to breakpoints within the getLegendSection function being undefined, added a simple if check to make sure both value and breakpoints are defined before attempting to run the for-loop. Also added an additional if check on data within the setMapGeographyColours function.
Link to ticket - https://trello.com/c/Dhj5JEUR/270-bug-unable-to-change-selected-geography
=> Fixed getLegendSection fn, added data check on DataLayer.

.vscode/extensions.json, .vscode/settings.json
This might be a tad excessive with the intellisense and githistory extensions but it's optional after all. The settings do help with the way Prettier is bundled into Svelte.
Fixes #126
=> Improve experience for VSCode devs

src/ui/CategorySelector/CategorySelector.svelte
…for both previous and next links if categories have a length of two or less.
Ticket: https://trello.com/c/Ufwawk06/267-fix-repetition-on-carousel-when-theres-only-two-options
Screenshots of functionality working locally.
=> Fix: Fixed categories repeating

src/ui/map/TileSet.svelte
**What**
Because the mapbox [ isSourceLoaded method returns error instead of false](https://github.com/mapbox/mapbox-gl-js/issues/9430) I believe that this issue can be fixed by only swapping the `isSourceLoaded` check with `getSource` inside of the custom `isSourceLoaded` function.
=> fixes the no source with ID map error - ticket#269

src/ui/Topic.svelte
aria-labelledBy and aria-describedBy are not valid for the div element unless the element has a role of "region" or "complementary" in this case the correct role is "region". 
Research and fix took from: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/region.html
=> Fix: Incorrect use of ARIA.

src/routes/[topicSlug].svelte, src/routes/[topicSlug]/[tableSlug]/[categorySlug].svelte, src/routes/area/index.svelte
There are page titles that are duplicated on multiple pages which may be confusing for screen reader users.
Screen reader comments:
“As I navigate through the service, I find that many of the page titles appear to have been named very similarly. I would prefer page titles to reflect page content more specifically.”
Solution:
Ensure that page titles are unique. This will ensure that screen reader users do not become disorientated.
Examples of this in practice.
https://deploy-preview-169--ons-data-map.netlify.app/health/general-health/very-good
https://deploy-preview-169--ons-data-map.netlify.app/area?location=E09000016
https://deploy-preview-169--ons-data-map.netlify.app/education
Signed off by design!
=> Fix: Smart page titles.

src/ui/SelectTopic.svelte
**What**
Updates the title of the suggestion component on the home screen from `Popular topic searches` to `Popular searches`.
=> Updates the title of the suggestion component on home screen-ticket#370
